[versions]
# renovate: depName=google/google-java-format
google-java-format = "1.19.2"

# Plugins
asciidoctor = "2.4.0"

[plugins]
# AsciiDoc-Support für Gradle (https://github.com/asciidoctor/asciidoctor-gradle-plugin)
asciidoctor-convert = { id = "org.asciidoctor.jvm.convert", version.ref = "asciidoctor" }
asciidoctor-pdf = { id = "org.asciidoctor.jvm.pdf", version.ref = "asciidoctor" }